events { 
    worker_connections 1024; 
} 
http { 
    server { 

        listen 80; 
            location /api/catalog/ { 
                proxy_pass http://catalog-service:5001/; 
            } 

            location /api/orders/ { 
                proxy_pass http://order-service:5002/; 
            } 

            location /api/deliveries/ { 
                proxy_pass http://delivery-service:5003/; 
            } 
            
            location /api/notifications/ { 
                proxy_pass http://notification-service:5004/; 
            } 
    }    
} 